# Generated by Django 2.2 on 2020-12-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solo_Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(default='What do you notice?', max_length=45)),
                ('content', models.TextField(default='Share what you observe about the image.')),
                ('list_item_number', models.IntegerField(default=0)),
                ('likes_allowed', models.BooleanField(default=False)),
                ('max_likes', models.IntegerField(default=0)),
                ('justification_required', models.BooleanField(default=False)),
                ('justification_text', models.TextField(default='I think this observation is significant because...')),
                ('like_same_day', models.BooleanField(default=False)),
                ('lesson_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_lessons', to='lessons.User')),
            ],
        ),
    ]
