# Generated by Django 2.2 on 2020-12-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_connect_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('number_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connect_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_posts', to='lessons.Connect_Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_posts', to='lessons.User')),
            ],
        ),
    ]
